CREATE DATABASE nextjsats;

\c nextjsats;
CREATE TABLE  sent_messages(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient VARCHAR,
    message VARCHAR
);
CREATE TABLE  senders(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender_id VARCHAR
);

CREATE DATABASE nextjsats_test WITH TEMPLATE nextjsats;